apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydemoapp
 labels:
   app: mydemoapp
spec:
 selector:
   matchLabels:
     app: mydemoapp
 replicas: 3
 template:
   metadata:
     labels:
       app: mydemoapp
   spec:
     containers:
     - name: mydemoapp
       image: acrdemo28.azurecr.io/aksdemo:demo
       resources:
         requests:
           cpu: 100m
           memory: 100Mi
         limits:
           cpu: 200m
           memory: 200Mi
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mydemoappservice
spec:
 type: LoadBalancer
 ports:
 - port: 8080
 selector:
   app: mydemoapp